
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 15 19:45:01 COT 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_decremento = 54;
  public static final int Op_atribucion = 38;
  public static final int Return = 11;
  public static final int Op_booleano = 55;
  public static final int Llave_c = 61;
  public static final int Llave_a = 60;
  public static final int Op_Xor_BaB = 76;
  public static final int Desplazamiento_Der = 59;
  public static final int Linea = 2;
  public static final int Coma = 66;
  public static final int Parent_c = 57;
  public static final int Parent_a = 56;
  public static final int Corchete_c = 63;
  public static final int Op_asig_suma = 3;
  public static final int Menorque = 42;
  public static final int Corchete_a = 62;
  public static final int True = 39;
  public static final int Long = 17;
  public static final int Punto = 67;
  public static final int Char = 18;
  public static final int For = 24;
  public static final int Void = 14;
  public static final int Igual_a = 43;
  public static final int Else = 21;
  public static final int Resta = 27;
  public static final int Int = 13;
  public static final int Op_And = 70;
  public static final int Cin = 49;
  public static final int Suma = 26;
  public static final int Using = 47;
  public static final int ERROR = 77;
  public static final int Cadena = 12;
  public static final int Main = 64;
  public static final int Op_asig_modulo = 5;
  public static final int Do = 22;
  public static final int Op_relacional = 35;
  public static final int Op_Not_BaB = 75;
  public static final int P_coma = 65;
  public static final int Mayorque = 41;
  public static final int Desplazamiento_Izq = 58;
  public static final int Scanf = 48;
  public static final int Case = 52;
  public static final int Op_Or_BaB = 74;
  public static final int Byte = 19;
  public static final int Menor_Igual = 46;
  public static final int Sistema = 37;
  public static final int Pause = 9;
  public static final int Op_Not = 72;
  public static final int If = 20;
  public static final int Mayor_Igual = 45;
  public static final int Define = 28;
  public static final int Op_Or = 71;
  public static final int EOF = 0;
  public static final int Cout = 50;
  public static final int Numero = 69;
  public static final int Double = 15;
  public static final int Struct = 29;
  public static final int Division = 33;
  public static final int Op_And_BaB = 73;
  public static final int Op_asig_multiplicacion = 4;
  public static final int error = 1;
  public static final int False = 40;
  public static final int Diferente = 44;
  public static final int Comillas = 10;
  public static final int Float = 16;
  public static final int Identificador = 68;
  public static final int Op_incremento = 53;
  public static final int Op_asig_resta = 7;
  public static final int Include = 8;
  public static final int Printf = 36;
  public static final int Register = 30;
  public static final int Op_asig_division = 6;
  public static final int Igual = 25;
  public static final int While = 23;
  public static final int Union = 31;
  public static final int Op_logico = 34;
  public static final int Multiplicacion = 32;
  public static final int Switch = 51;
}

