
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 09 14:46:34 COT 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 19;
  public static final int S_coma = 33;
  public static final int Llave_c = 27;
  public static final int Op_booleano = 23;
  public static final int Llave_a = 26;
  public static final int If = 6;
  public static final int Void = 12;
  public static final int T_dato = 4;
  public static final int Else = 7;
  public static final int Corchete_c = 29;
  public static final int Corchete_a = 28;
  public static final int Punto = 32;
  public static final int Parent_c = 25;
  public static final int Parent_a = 24;
  public static final int While = 9;
  public static final int Division = 17;
  public static final int Int = 11;
  public static final int Cadena = 5;
  public static final int For = 10;
  public static final int EOF = 0;
  public static final int P_coma = 31;
  public static final int Printf = 20;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int Op_atribucion = 21;
  public static final int ERROR = 36;
  public static final int Do = 8;
  public static final int Op_logico = 18;
  public static final int Identificador = 34;
  public static final int Resta = 15;
  public static final int Multiplicacion = 16;
  public static final int Op_incremento = 22;
  public static final int Numero = 35;
  public static final int Suma = 14;
  public static final int Main = 30;
  public static final int Igual = 13;
  public static final int Comillas = 3;
}

